import type { ServerManager } from '../../../http-server/server-manager/types'
import type { StaticAssetManifestEntry } from '../../../http-server/static-assets'
import type { StaticAssetSession } from '../../../http-server/static-assets/types'

import { createStaticAssetService } from '../../../http-server/static-assets'
import { buildMountedStaticAssetPath } from '../../../http-server/static-assets/paths'

/**
 * Describes one plugin asset session creation request.
 *
 * Use when:
 * - A plugin-owned asset URL must be mounted behind the local loopback server with cookie auth
 * - Snapshot builders need a transport-agnostic way to authorize one plugin asset route before iframe load
 *
 * Expects:
 * - `pluginId` matches a manifest entry registered in the asset host
 * - `routeAssetPath` identifies the iframe entry asset relative to the mounted `/ui` route
 * - `pathPrefix` is scoped to the mounted route prefix accepted by the session store
 *
 * Returns:
 * - N/A
 */
export interface PluginAssetSessionInput {
  /** Plugin id that owns the static asset root. */
  pluginId: string
  /** Plugin version expected by the server-side session validator. */
  version: string
  /** Parent plugin session id used for owner-scoped revocation. */
  ownerSessionId: string
  /** Asset path to mount in the returned renderer-facing URL. */
  routeAssetPath: string
  /** Allowed asset path prefix enforced by the server-side session store. */
  pathPrefix: string
  /** Session lifetime in milliseconds from creation or refresh time. */
  ttlMs: number
}

/**
 * Describes the cookie material Electron must apply before loading a plugin asset URL.
 *
 * Use when:
 * - Main process bridges server-side asset sessions into Electron's cookie jar
 * - Revocation needs enough cookie identity to remove previously issued asset cookies
 *
 * Expects:
 * - `url` belongs to the local asset server origin
 * - `path` matches the server-issued cookie path for the asset session route
 *
 * Returns:
 * - N/A
 */
export interface PluginAssetCookie {
  /** Cookie name generated for the asset session. */
  name: string
  /** Opaque cookie value required by the static asset route. */
  value: string
  /** Absolute URL on the local asset server used by Electron cookie APIs. */
  url: string
  /** Route path scope generated by the asset session store. */
  path: string
  /** Unix timestamp in milliseconds when the cookie-backed asset session expires. */
  expiresAt: number
}

/**
 * Applies and removes plugin asset cookies from the Electron host.
 *
 * Use when:
 * - Asset sessions must exist in Electron's cookie jar before an iframe navigates to its URL
 * - Asset session revocation must remove browser-visible cookie state
 *
 * Expects:
 * - `setCookie` resolves only after Electron can send the cookie for matching asset URLs
 * - `removeCookie` is idempotent for already-removed cookies
 *
 * Returns:
 * - N/A
 */
export interface PluginAssetCookieAdapter {
  setCookie: (cookie: PluginAssetCookie) => Promise<void>
  removeCookie: (cookie: PluginAssetCookie) => Promise<void>
}

/**
 * Describes the plugin asset methods needed while building renderer-facing snapshots.
 *
 * Use when:
 * - Snapshot builders must request route-scoped asset sessions without depending on HTTP server internals
 * - Host bootstrap wants to layer caching or policy on top of the raw asset transport
 *
 * Expects:
 * - `routeAssetPath` identifies the mounted asset file being exposed in the snapshot
 * - Implementations set host cookies before returning renderer-facing URLs
 *
 * Returns:
 * - A mounted asset URL and cookie-backed session metadata
 */
export interface PluginAssetSnapshotService {
  getBaseUrl: () => string | undefined
  createAssetSession: (input: Omit<PluginAssetSessionInput, 'ttlMs'>) => Promise<PluginAssetSession>
}

/**
 * Describes a plugin asset session prepared for renderer iframe navigation.
 *
 * Use when:
 * - A plugin iframe needs a mounted static asset URL and pre-applied cookie state
 * - Callers need the opaque session id for later targeted revocation
 *
 * Expects:
 * - `cookie` was set through the host adapter before the value is returned
 *
 * Returns:
 * - Renderer-facing URL plus server and cookie metadata
 */
export interface PluginAssetSession {
  /** Absolute mounted asset URL safe to hand to a renderer iframe after cookie setup. */
  url: string
  /** Opaque server-side asset session id embedded in mounted asset routes. */
  assetSessionId: string
  /** Cookie data that was applied through the host adapter. */
  cookie: PluginAssetCookie
  /** Unix timestamp in milliseconds when the cookie-backed asset session expires. */
  expiresAt: number
}

/**
 * Defines the plugin-owned asset hosting service used by the plugin host.
 *
 * Use when:
 * - Plugin snapshots need mounted asset URLs without depending on the H3 server shape
 * - Host teardown must revoke plugin asset access independently from widget/gamelet logic
 *
 * Expects:
 * - Implementations own the underlying transport, cookie, and session lifecycle
 *
 * Returns:
 * - A startable/stoppable asset-hosting service with generic plugin-facing methods
 */
export interface PluginAssetService extends ServerManager {
  getBaseUrl: () => string | undefined
  createAssetSession: (input: PluginAssetSessionInput) => Promise<PluginAssetSession>
  revokeSession: (assetSessionId: string) => Promise<void>
  revokeByOwnerSessionId: (ownerSessionId: string) => Promise<void>
  revokeByPluginId: (pluginId: string) => Promise<void>
  revokeAll: () => Promise<void>
}

function createPluginAssetCookie(baseUrl: string, session: StaticAssetSession): PluginAssetCookie {
  return {
    name: session.cookieName,
    value: session.cookieValue,
    url: new URL(session.cookiePath, baseUrl).toString(),
    path: session.cookiePath,
    expiresAt: session.expiresAt,
  }
}

function requireBaseUrl(baseUrl: string | undefined) {
  if (!baseUrl) {
    throw new Error('Plugin asset server base URL is unavailable; start the asset server before creating asset sessions')
  }

  return baseUrl
}

async function removeCookies(cookieAdapter: PluginAssetCookieAdapter, baseUrl: string, sessions: readonly StaticAssetSession[]) {
  await Promise.all(sessions.map(session => cookieAdapter.removeCookie(createPluginAssetCookie(baseUrl, session))))
}

/**
 * Creates the plugin asset host service backed by the extension static asset server.
 *
 * Use when:
 * - The plugin host needs to expose mounted asset URLs to renderer snapshots
 * - Asset session lifecycle should stay inside the plugin domain instead of the HTTP server layer
 *
 * Expects:
 * - `getManifestEntryByName` returns the latest plugin root/version map
 * - `cookieAdapter` writes and removes cookies in the Electron host session used by plugin iframes
 *
 * Returns:
 * - A plugin-facing asset host service with generic plugin asset methods
 */
export function createPluginAssetService(options: {
  getManifestEntryByName: () => Map<string, StaticAssetManifestEntry>
  cookieAdapter: PluginAssetCookieAdapter
}): PluginAssetService {
  const server = createStaticAssetService({ getManifestEntryByName: options.getManifestEntryByName })
  let lastBaseUrl: string | undefined

  const readBaseUrl = () => {
    const baseUrl = server.getBaseUrl()
    lastBaseUrl = baseUrl ?? lastBaseUrl
    return baseUrl
  }

  const revokeSessions = async (sessions: readonly StaticAssetSession[]) => {
    const baseUrl = readBaseUrl() ?? lastBaseUrl
    if (!baseUrl) {
      return
    }

    await removeCookies(options.cookieAdapter, baseUrl, sessions)
  }

  return {
    key: 'plugin-assets',
    async start() {
      await server.start()
    },
    async stop() {
      await revokeSessions(server.revokeAll())
      await server.stop()
    },
    getBaseUrl() {
      return readBaseUrl()
    },
    async createAssetSession(input) {
      const session = server.createSession({
        extensionId: input.pluginId,
        version: input.version,
        ownerSessionId: input.ownerSessionId,
        pathPrefix: input.pathPrefix,
        ttlMs: input.ttlMs,
      })

      try {
        const baseUrl = requireBaseUrl(readBaseUrl())
        const mountedPath = buildMountedStaticAssetPath({
          extensionId: input.pluginId,
          assetSessionId: session.assetSessionId,
          assetPath: input.routeAssetPath,
        })

        if (!mountedPath) {
          throw new RangeError('Plugin asset session routeAssetPath must be a safe plugin asset path')
        }

        const cookie = createPluginAssetCookie(baseUrl, session)
        await options.cookieAdapter.setCookie(cookie)

        return {
          url: new URL(mountedPath, baseUrl).toString(),
          assetSessionId: session.assetSessionId,
          cookie,
          expiresAt: session.expiresAt,
        }
      }
      catch (error) {
        server.revokeSession(session.assetSessionId)
        throw error
      }
    },
    async revokeSession(assetSessionId) {
      const session = server.revokeSession(assetSessionId)
      if (!session) {
        return
      }

      await revokeSessions([session])
    },
    async revokeByOwnerSessionId(ownerSessionId) {
      await revokeSessions(server.revokeByOwnerSessionId(ownerSessionId))
    },
    async revokeByPluginId(pluginId) {
      await revokeSessions(server.revokeByExtensionId(pluginId))
    },
    async revokeAll() {
      await revokeSessions(server.revokeAll())
    },
  }
}
